/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoTypingPreview: typeof import('./src/components/game/AutoTypingPreview.vue')['default']
    ComplaintInput: typeof import('./src/components/game/ComplaintInput.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navbar: typeof import('./src/components/base/Navbar.vue')['default']
    PointsPopup: typeof import('./src/components/game/PointsPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveManager: typeof import('./src/components/game/SaveManager.vue')['default']
    Toast: typeof import('./src/components/base/Toast.vue')['default']
    UpgradeCard: typeof import('./src/components/game/UpgradeCard.vue')['default']
    Upgrades: typeof import('./src/components/game/Upgrades.vue')['default']
  }
}
